### ISSUE TITLE
Request: Changing Host name in something like culfw-esp8266

### ISSUE THREAD

**Issue by kroon040** [Man-fred/culfw-esp8266#5]
request:

Change the hostname . Now it takes EPS-mac adress. Should be more nice to call it culfw-esp8266

**Comment by Man-fred** [comment]
in commit #8152473 is the change to give the device a free name up to 32 characters. But it is not sure that the nameserver use this device-name. With fixed ip-address the nameserver will not use the name.

**Comment by kroon040** [comment]
tried to compile new version but got some errors:

`Arduino: 1.8.12 (Linux), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:109:0:
/home/richard/Arduino/libraries/rf_asksin/rf_asksin.h:25:22: note: 'RfAsksinClass RfAsksin' declared here
 extern RfAsksinClass RfAsksin;
                      ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:86:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
 extern FNCOLLECTIONClass FNcol;
                          ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:84:0:
/home/richard/Arduino/libraries/cc1100/cc1100.h:41:20: note: 'CC1100Class CC1100' declared here
 extern CC1100Class CC1100;
                    ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:86:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
 extern FNCOLLECTIONClass FNcol;
                          ^
In file included from /home/richard/Arduino/libraries/clock/clock.h:26:0,
                 from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:
/home/richard/Arduino/libraries/rf_send/rf_send.h:35:20: note: 'RfSendClass RfSend' declared here
 extern RfSendClass RfSend;
                    ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:95:0:
/home/richard/Arduino/libraries/fastrf/fastrf.h:17:20: note: 'FastRFClass FastRF' declared here
 extern FastRFClass FastRF;
                    ^
In file included from /home/richard/Arduino/libraries/clock/clock.h:26:0,
                 from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:
/home/richard/Arduino/libraries/rf_send/rf_send.h:35:20: note: 'RfSendClass RfSend' declared here
 extern RfSendClass RfSend;
                    ^
/home/richard/Arduino/libraries/rf_send/rf_send.h:35:20: note: 'RfSendClass RfSend' declared here
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:86:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
 extern FNCOLLECTIONClass FNcol;
                          ^
In file included from /home/richard/Arduino/libraries/clock/clock.h:26:0,
                 from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:
/home/richard/Arduino/libraries/rf_send/rf_send.h:35:20: note: 'RfSendClass RfSend' declared here
 extern RfSendClass RfSend;
                    ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:106:0:
/home/richard/Arduino/libraries/memory/memory.h:12:20: note: 'MemoryClass Memory' declared here
 extern MemoryClass Memory;
                    ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:118:0:
/home/richard/Arduino/libraries/rf_native/rf_native.h:22:22: note: 'RfNativeClass RfNative' declared here
 extern RfNativeClass RfNative;
                      ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:100:0:
/home/richard/Arduino/libraries/ethernet/ethernet.h:83:22: note: 'EthernetClass Ethernet' declared here
 extern EthernetClass Ethernet;
                      ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:86:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
 extern FNCOLLECTIONClass FNcol;
                          ^
In file included from /home/richard/Arduino/libraries/clock/clock.h:23:0,
                 from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:
/home/richard/Arduino/libraries/fht/fht.h:92:18: note: 'FHTClass FHT' declared here
  extern FHTClass FHT;
                  ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:0:
/home/richard/Arduino/libraries/clock/clock.h:76:19: note: 'CLOCKClass CLOCK' declared here
 extern CLOCKClass CLOCK;
                   ^
In file included from /home/richard/Arduino/libraries/clock/clock.h:34:0,
                 from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:88:
/home/richard/Arduino/libraries/rf_router/rf_router.h:51:22: note: 'RfRouterClass RfRouter' declared here
 extern RfRouterClass RfRouter;
                      ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:86:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
 extern FNCOLLECTIONClass FNcol;
                          ^
/home/richard/Arduino/libraries/fncollection/fncollection.h:33:26: note: 'FNCOLLECTIONClass FNcol' declared here
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:91:0:
/home/richard/Arduino/libraries/rf_receive/rf_receive.h:152:23: note: 'RfReceiveClass RfReceive' declared here
 extern RfReceiveClass RfReceive;
                       ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:84:0:
/home/richard/Arduino/libraries/cc1100/cc1100.h:41:20: note: 'CC1100Class CC1100' declared here
 extern CC1100Class CC1100;
                    ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:112:0:
/home/richard/Arduino/libraries/rf_moritz/rf_moritz.h:27:22: note: 'RfMoritzClass Moritz' declared here
 extern RfMoritzClass Moritz;
                      ^
In file included from /home/richard/Downloads/culfw-esp8266-master/culfw-esp8266/culfw-esp8266.ino:100:0:
/home/richard/Arduino/libraries/ethernet/ethernet.h:83:22: note: 'EthernetClass Ethernet' declared here
 extern EthernetClass Ethernet;
                      ^
/home/richard/Arduino/libraries/ethernet/ethernet.cpp: In member function 'void EthernetClass::ewip(const uint16_t*, uint8_t*)':
/home/richard/Arduino/libraries/ethernet/ethernet.cpp:358:17: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'uint8_t {aka unsigned char}' [-fpermissive]
   FNcol.ewb(addr+1, ip[0]>>8);
                 ^
In file included from /home/richard/Arduino/libraries/ethernet/ethernet.cpp:8:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:14:7: error:   initializing argument 1 of 'void FNCOLLECTIONClass::ewb(uint8_t, uint8_t)' [-fpermissive]
  void ewb(uint8_t p, uint8_t v);
       ^
/home/richard/Arduino/libraries/ethernet/ethernet.cpp:359:17: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'uint8_t {aka unsigned char}' [-fpermissive]
   FNcol.ewb(addr+0, ip[0]&0xff);
                 ^
In file included from /home/richard/Arduino/libraries/ethernet/ethernet.cpp:8:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:14:7: error:   initializing argument 1 of 'void FNCOLLECTIONClass::ewb(uint8_t, uint8_t)' [-fpermissive]
  void ewb(uint8_t p, uint8_t v);
       ^
/home/richard/Arduino/libraries/ethernet/ethernet.cpp:360:17: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'uint8_t {aka unsigned char}' [-fpermissive]
   FNcol.ewb(addr+3, ip[1]>>8);
                 ^
In file included from /home/richard/Arduino/libraries/ethernet/ethernet.cpp:8:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:14:7: error:   initializing argument 1 of 'void FNCOLLECTIONClass::ewb(uint8_t, uint8_t)' [-fpermissive]
  void ewb(uint8_t p, uint8_t v);
       ^
/home/richard/Arduino/libraries/ethernet/ethernet.cpp:361:17: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'uint8_t {aka unsigned char}' [-fpermissive]
   FNcol.ewb(addr+2, ip[1]&0xff);
                 ^
In file included from /home/richard/Arduino/libraries/ethernet/ethernet.cpp:8:0:
/home/richard/Arduino/libraries/fncollection/fncollection.h:14:7: error:   initializing argument 1 of 'void FNCOLLECTIONClass::ewb(uint8_t, uint8_t)' [-fpermissive]
  void ewb(uint8_t p, uint8_t v);
       ^
Multiple libraries were found for "WiFiUdp.h"
 Used: /home/richard/.arduino15/packages/esp8266/hardware/esp8266/2.6.3/libraries/ESP8266WiFi
 Not used: /home/richard/Downloads/arduino-1.8.12/libraries/WiFi
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by Man-fred** [comment]
too late yesterday ;) . Now I compiled twice and also with fresh pulled git and all seems ok.

Why there are so many "note:" I can't say.

**Comment by kroon040** [comment]
compile works, with the notes, and also hostname is now ok.
